[project]
name = "lox-interpreter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "FedericoCantarelli", email = "fede.cantarelli98@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.1",
]

[project.scripts]
lox = "lox_interpreter:main"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver2"
version_provider = "pep621"
update_changelog_on_bump = true
major_version_zero = true
